// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

import "time"

type Server struct {
	Name              string    `json:"name"`
	TailscaleHostname string    `json:"tailscale_hostname"`
	HetznerID         int64     `json:"hetzner_id"`
	Ip                string    `json:"ip"`
	AgentToken        string    `json:"agent_token"`
	SshKeyID          int64     `json:"ssh_key_id"`
	FirewallID        int64     `json:"firewall_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type Service struct {
	Name       string    `json:"name"`
	ServerName string    `json:"server_name"`
	Domain     string    `json:"domain"`
	Status     string    `json:"status"`
	SpecJson   string    `json:"spec_json"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
