// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

import "context"

const createServer = `-- name: CreateServer :exec
INSERT INTO servers (
  name, tailscale_hostname, hetzner_id, ip, agent_token, ssh_key_id, firewall_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type CreateServerParams struct {
	Name              string `json:"name"`
	TailscaleHostname string `json:"tailscale_hostname"`
	HetznerID         int64  `json:"hetzner_id"`
	IP                string `json:"ip"`
	AgentToken        string `json:"agent_token"`
	SSHKeyID          int64  `json:"ssh_key_id"`
	FirewallID        int64  `json:"firewall_id"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer,
		arg.Name,
		arg.TailscaleHostname,
		arg.HetznerID,
		arg.IP,
		arg.AgentToken,
		arg.SSHKeyID,
		arg.FirewallID,
	)
	return err
}

const deleteServerByName = `-- name: DeleteServerByName :exec
DELETE FROM servers
WHERE name = $1
`

func (q *Queries) DeleteServerByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteServerByName, name)
	return err
}

const getServerByName = `-- name: GetServerByName :one
SELECT name, tailscale_hostname, hetzner_id, ip, agent_token, ssh_key_id, firewall_id, created_at
FROM servers
WHERE name = $1
`

func (q *Queries) GetServerByName(ctx context.Context, name string) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByName, name)
	var i Server
	err := row.Scan(
		&i.Name,
		&i.TailscaleHostname,
		&i.HetznerID,
		&i.Ip,
		&i.AgentToken,
		&i.SshKeyID,
		&i.FirewallID,
		&i.CreatedAt,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT name, tailscale_hostname, hetzner_id, ip, agent_token, ssh_key_id, firewall_id, created_at
FROM servers
ORDER BY created_at ASC
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.Name,
			&i.TailscaleHostname,
			&i.HetznerID,
			&i.Ip,
			&i.AgentToken,
			&i.SshKeyID,
			&i.FirewallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if items == nil {
		return []Server{}, nil
	}
	return items, nil
}
