// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

import "context"

const deleteServiceByName = `-- name: DeleteServiceByName :exec
DELETE FROM services
WHERE name = $1
`

func (q *Queries) DeleteServiceByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceByName, name)
	return err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT name, server_name, domain, status, spec_json, created_at, updated_at
FROM services
WHERE name = $1
`

func (q *Queries) GetServiceByName(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByName, name)
	var i Service
	err := row.Scan(
		&i.Name,
		&i.ServerName,
		&i.Domain,
		&i.Status,
		&i.SpecJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT name, server_name, domain, status, spec_json, created_at, updated_at
FROM services
ORDER BY created_at ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.Name,
			&i.ServerName,
			&i.Domain,
			&i.Status,
			&i.SpecJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if items == nil {
		return []Service{}, nil
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO services (
  name, server_name, domain, status, spec_json
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (name)
DO UPDATE SET
  server_name = excluded.server_name,
  domain = excluded.domain,
  status = excluded.status,
  spec_json = excluded.spec_json,
  updated_at = NOW()
`

type UpsertServiceParams struct {
	Name       string `json:"name"`
	ServerName string `json:"server_name"`
	Domain     string `json:"domain"`
	Status     string `json:"status"`
	SpecJson   string `json:"spec_json"`
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertService,
		arg.Name,
		arg.ServerName,
		arg.Domain,
		arg.Status,
		arg.SpecJson,
	)
	return err
}
